version: '3'

services:

  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  kafka:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.2.15
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.2.15:9092
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_BROKER_ID: 100
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
